// Public client portal configuration.
// Replace these two values with your Supabase Project URL and anon/publishable key.
// Never put the service_role key in this file.
const SUPABASE_URL = "https://rxsewqbmxmnuorguyakp.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_FzTtGkxmvmKSQXcEY13UtA_uhb8QQCN";
const form=document.getElementById("lookup"),btn=document.getElementById("submit"),errorBox=document.getElementById("error"),result=document.getElementById("result"),details=document.getElementById("details");
const money=(v,c="GBP")=>new Intl.NumberFormat("en-GB",{style:"currency",currency:c||"GBP"}).format(Number(v||0));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
form.addEventListener("submit",async e=>{e.preventDefault();errorBox.textContent="";result.style.display="none";
if(SUPABASE_URL.startsWith("PASTE_")||SUPABASE_ANON_KEY.startsWith("PASTE_")){errorBox.textContent="The invoice portal has not been connected to the company database yet.";return}
btn.disabled=true;btn.textContent="Checking…";
try{const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const {data,error}=await client.rpc("lookup_client_invoice",{p_number:document.getElementById("number").value.trim(),p_email:document.getElementById("email").value.trim()});
if(error)throw error;if(!data||!data.length){errorBox.textContent="Invoice not found. Please check the invoice number and registered email address.";return}
const d=data[0];const total=Math.max(0,Number(d.total||0));const paid=Math.min(total,Math.max(0,Number(d.paid_amount||0)));const invoiceBalance=Math.max(0,total-paid);details.innerHTML=`<div class="rows"><span>Invoice number</span><b>${esc(d.invoice_number)}</b></div><div class="rows"><span>Client</span><b>${esc(d.client_name)}</b></div><div class="rows"><span>Project</span><b>${esc(d.project_name||"—")}</b></div><div class="rows"><span>Invoice date</span><b>${esc(d.invoice_date||"—")}</b></div><div class="rows"><span>Payment due</span><b>${esc(d.due_date||"—")}</b></div><div class="rows"><span>Status</span><b>${esc(d.status)}</b></div><div class="rows"><span>Subtotal</span><b>${money(d.subtotal,d.currency)}</b></div><div class="rows"><span>VAT</span><b>${Number(d.vat_rate||0)>0?money(d.vat,d.currency):"Not charged"}</b></div><div class="rows"><span>Total invoice</span><b>${money(total,d.currency)}</b></div><div class="rows"><span>Payment received against this invoice</span><b>${money(paid,d.currency)}</b></div><div class="balance"><span>This invoice balance due</span><strong>${money(invoiceBalance,d.currency)}</strong></div>${Number(d.contract_total||0)>0?`<h2 style="margin-top:20px">Contract balance summary</h2><div class="rows"><span>Total contract amount</span><b>${money(d.contract_total,d.currency)}</b></div><div class="rows"><span>Previously invoiced</span><b>${money(d.previously_invoiced,d.currency)}</b></div><div class="rows"><span>Current invoice total</span><b>${money(total,d.currency)}</b></div><div class="rows"><span>Payment received to date</span><b>${money(d.paid_to_date,d.currency)}</b></div><div class="balance"><span>Remaining contract after this invoice</span><strong>${money(d.remaining_to_invoice,d.currency)}</strong></div>`:""}`;
result.style.display="block";
}catch(err){errorBox.textContent="Unable to check the invoice right now. Please try again later."}finally{btn.disabled=false;btn.textContent="View invoice"}});
